import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets:['latin'],
  weight:["100","200","300","400","500","600","700","800"],
  variable:'--font-jetbrainsMono'
})

export const metadata = {
  title: "Adnan Jafri - Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
      <div className="flex float-right m-6 mr-20"> 
      <span className="bg-[#FF671F] w-[20px] h-[20px] rounded-full cursor-pointer mr-2"></span>
      <span className="bg-[#FFffff] w-[20px] h-[20px] rounded-full cursor-pointer mr-2"></span> 
        <span className="bg-accent w-[20px] h-[20px] rounded-full  cursor-pointer"></span>
        
      </div>
        <Header/>
        <StairTransition/>
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
